disabled_rules:
  - line_length
  - force_unwrapping
  - nesting
  - weak_delegate
  - empty_string
  - todo
  - trailing_whitespace
  - modifier_order
opt_in_rules:
  - block_based_kvo
  - class_delegate_protocol
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - identical_operands
  - joined_default_parameter
  - modifier_order
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - toggle_bool
  - unused_private_declaration
  - identifier_name
  - force_cast
  - force_try
  
operator_usage_whitespace: error
syntactic_sugar: error
trailing_comma:
  severity: error
trailing_newline: error
trailing_semicolon: error
trailing_whitespace: error
unused_closure_parameter: error
unused_optional_binding:
  severity: error
vertical_whitespace:
  severity: error
file_length:
  warning: 600
  error: 1200
function_body_length:
  warning: 50
  error: 70
type_body_length:
  warning: 300
  error: 400
type_name:
  max_length: # warning and error
    warning: 50
    error: 60
object_literal:
  color_literal: false
  image_literal: false
identifier_name:
  excluded:
    - id
    - ip
    - os
    - f5
    - qa
    - to
    - up
    - or
    - in
    - y
    - x
    - xy
    - db
    - no
    - on

excluded:
- ${SRCROOT}/Pods
- ${SRCROOT}/bundle
- ${SRCROOT}/${PROJECT_NAME}Tests
- ${SRCROOT}/${PROJECT_NAME}UITests
